name: Will Hoffer
title: Will Hoffer
description: Mathematical Physicist & Fractal Geometer
theme: jekyll-theme-cayman
markdown: kramdown
permalink: /:year-:month-:day/:title/

google_analytics: UA-159371398-1

footer-links:
  email: whoff003@gmail.com
  github: willhoffer
  rss: 
  #stackoverflow: "users/11308570/wyvellum

# Build Settings
exclude: ['*.Rmd']
