---
title: "Post Template"
author: "Will Hoffer"
date: "February 29, 2020"  # DO NOT USE Sys.Date()
output:                    # DO NOT CHANGE
  prettydoc::html_pretty:  # DO NOT CHANGE
    theme: cayman          # DO NOT CHANGE
    highlight: github      # DO NOT CHANGE
header-includes: \usepackage{instrumenta}
---

## A Template for Posts

Here, I have created a document to be copied for future posts. In it, I include some helpful syntax tricks as well.

## Common Syntax

I refer the reader to the following links for some examples of sytax: [some basics](https://www.markdownguide.org/basic-syntax) and [more features](https://www.markdownguide.org/extended-syntax). I provide a few examples.

#### Tables
The following code produces the table depicted.
```
| A | B | C |
|---|---|---|
| D | E | F |
| G | H | I |
```
| A | B | C |
|---|---|---|
| D | E | F |
| G | H | I |
There are additional options available, such as changing relative width of columns.

### Footnotes
Footnotes can be created using a reference of the form `[^n]` placed exactly where the footnote should appear, together with a definition somewhere in the document of what text should appear in the footnote in the syntax:
```
[^1]: The text the shows at the bottom of the page.
```
The footnote does not need to be placed at the end of the markdown document. Also, `n` may be replaced by any number or a word without any spaces; it is just a label for the footnote to be repeated in the later definition. Footnotes are numbered sequentially as they appear in the document.

## Using $\LaTeX$
Firstly, note that as above, it is possible to include $\LaTeX$ in a header. Inline $\LaTeX$ is acheived by using a single pair of `$ $` with relevant code in between. Note that markdown immediately assumes the code is in math mode. Full equations which appear on their own centered line can be acheived using either the `$$ $$` or `\[   \]` syntax. 

#### Divergence of the Harmonic Series
$$ \sum_{n=1}^\infty \frac{1}{n}=\infty $$

#### Solution of the Basel Problem
\[ \sum_{n=1}^\infty \frac{1}{n^2}=\frac{\pi^2}{6}\] 


## Collapsable Proofs

The `<details>` tag enables text to be made collapsable. Adding a `<summary>` tag enables one to specify text to be displayed for showing/hiding the block of text.

I provide an elementary theorem with its proof as a nice example.

#### Infinitude of Primes
**Theorem:** There are infinitely many prime numbers.

<details><summary>Euclid's Proof</summary>
Consider any finite list of primes, be given by $p_1,p_2,...,p_n$. Define a new number as follows:
$$q=1+\prod_{i=1}^n p_i$$
Clearly $q$ is distinct from all of the $p_i$'s we have listed. Moreover, $q$ has the following property: if $x|q$ and $x|\prod p_i$, then $x=1$. Indeed, if $x$ divides two numbers, it must also divide their difference given by $q-\prod p_i=1$, and the only (positive) divisor of $1$ is itself.

Observe the dichotomy of cases:

- If $q$ is prime, we have found a new, unlisted prime. 
- If $q$ is not prime, then it must have a prime factor $p$ for which $p|q$. Note that $p\neq 1$ cannot divide the product of listed primes by the lemma. Hence $p$ is distinct from all of the listed primes appearing in the product; $p$ is a new, unlisted prime.

Therefore, given any list of primes, we may always find another prime not on the list. $\square$[^cd]
</details>

[^cd]: Note that Euclid's proof is in fact constructive, so I use $\square$ over ⚔. Often, authors use a proof by contradiction variant of this argument by assuming the list contains *all* prime numbers.


